adding my lab with the horse racing
d3nnyyy/HorseRacingLab pull request #1
Opened 2022-12-01 00:13 UTC by d3nnyyy

2022-12-12 07:04 UTC, Andriy723 commented on Race.cpp
> +using namespace std;
After "RaceHouse.h" there should be an empty line then the namespace std

2022-12-12 07:16 UTC, Andriy723 commented on Race.h
> +#include "RaceHorse.h"
There must be an empty line before "RaceHouse.h"

2022-12-12 07:17 UTC, Andriy723 commented on Race.h
> +#include <list>
There must be an empty line after "RaceHouse.h"

2022-12-12 07:22 UTC, Andriy723 commented on RaceHorse.h
> +using namespace std;
After define there should be an empty line

2022-12-12 07:25 UTC, Andriy723 commented on RaceHorse.h
> +#include <iostream>
There should be an empty line after namespace std

2022-12-12 07:26 UTC, Andriy723 commented on main.cpp
> +#include <math.h>
There should be an empty line after <math.h>

2022-12-12 07:34 UTC, Andriy723 commented on main.cpp
> +
There should not be an empty line

2022-12-12 07:34 UTC, Andriy723 commented on main.cpp
> +
There should not be an empty line

2022-12-12 07:35 UTC, Andriy723 commented on main.cpp
> +
There should not be an empty line

2022-12-12 07:35 UTC, Andriy723 commented on main.cpp
> +
There should not be an empty line

2022-12-12 08:00 UTC, Andriy723 requested changes
There are no indents, lowercase methods

2022-12-21 17:40 UTC, Andriy723 approved these changes
All problems that i noticed were resolved. Good job!

2023-02-22 23:22 UTC, zveres-ss requested changes

2023-02-22 23:22 UTC, zveres-ss commented on main.cpp
> +        while (place != 4)
4 is magic number, make it as constant with well defined name

2023-09-09 09:17 UTC, merged